version: '3.4'

services:
  mfstreamkaraoke:
    image: mfstreamkaraoke
    build:
      context: stream-karaoke/mf-stream-karaoke
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4212:4212
